In [1]:
# Importing modules

import pandas as pd # for data wrangling
import seaborn as sns # for plotting
import matplotlib.pyplot as plt # for plotting
import missingno as msno # for visualizing missing values in data
import numpy as np # for array computations

plt.style.use('ggplot') # setting style for matplotlib

In [2]:
# importing model specific libraries

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.grid_search import GridSearchCV


/home/arrayslayer/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/arrayslayer/anaconda3/lib/python3.6/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [3]:
cd train

/home/arrayslayer/ML Competitions/Codefest/train


In [4]:
#importing merged and integral dataset

train_df = pd.read_csv('merged_and_categorical.csv')
train_df.dropna(inplace=True)

In [5]:
# training output

Y_train = train_df['attempts_range']
Y_train = Y_train.astype(int)

In [6]:
# adding new features

train_df['level_rating'] = train_df['max_rating'] * train_df['level_type']

In [7]:
train_df['points'] = train_df['points'] ** 2

In [8]:
# training input dataset

X_train = train_df[['submission_count', 'contribution', 'country', 'follower_count',
       'last_online_time_seconds', 'max_rating', 'registration_time_seconds',
       'level_type', 'points','level_rating']]

In [9]:
# impprting test dataset that matches train dataset properties

test_df = pd.read_csv('test_merged.csv')

In [10]:
# Retaining only those rows that have ID as a legit input
test_df = test_df[pd.notnull(test_df['ID'])]

In [11]:
# adding new features

test_df['level_rating'] = test_df['max_rating'] * test_df['level_type']

In [12]:
test_df['points'] = test_df['points']**2

In [13]:
# testing input dataset

X_test = test_df[['submission_count', 'contribution', 'country', 'follower_count',
       'last_online_time_seconds', 'max_rating', 'registration_time_seconds',
       'level_type', 'points','level_rating']]

In [32]:
# trying KNN
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=700)
scores = cross_val_score(neigh, X_train, Y_train, cv=2, scoring='accuracy')
scores


array([ 0.54322398,  0.54295691])

In [45]:
# Grid Search CV

rfc = RandomForestClassifier(n_jobs=3,max_features= 'auto' ,n_estimators=50,max_depth=10,oob_score = True) 

param_grid = { 
    'min_samples_split' : [4,6,8]
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X_train, Y_train)
print(CV_rfc.best_params_)

{'min_samples_split': 8}


In [ ]:
# check feature imp, get fenuls columns

In [11]:
# Training and performing cross validation


rf = RandomForestClassifier(n_estimators=500,max_depth =10, min_samples_split= 8,max_features='auto' )
scores = cross_val_score(rf, X_train, Y_train, cv=2, scoring='accuracy')
scores

array([ 0.5434303,  0.5334656])

In [14]:
rf = RandomForestClassifier(n_estimators=800,max_depth =10, min_samples_split= 8,max_features='auto' )

In [50]:
# Training and performing cross validation
scores = cross_val_score(rf, X_train, Y_train, cv=3, scoring='accuracy')
scores

array([ 0.54420587,  0.53652033,  0.54073616])

In [33]:
neigh.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=700, p=2,
           weights='uniform')

In [37]:
X_train.columns

Index(['submission_count', 'contribution', 'country', 'follower_count',
       'last_online_time_seconds', 'max_rating', 'registration_time_seconds',
       'level_type', 'points', 'level_rating'],
      dtype='object')

 500.0     52566
 1000.0    31992
 1500.0    16783
 2000.0     7950
 750.0      4456
 1750.0     3147
 2500.0     3030
 1250.0     3008
 2250.0     1099
 250.0       791
 3000.0      594
 2750.0      359
 3.0         133
 3250.0       58
 3500.0       33
 8.0           8
 5.0           4
-1.0           1
 10.0          1
 5000.0        1
Name: points, dtype: int64

In [48]:
rf.feature_importances_

array([ 0.06708192,  0.03553937,  0.03600823,  0.05591853,  0.06049438,
        0.13314683,  0.0827962 ,  0.12561419,  0.22454244,  0.17885792])

In [36]:
#filling in missing values

X_test = X_test.fillna(method='bfill')
X_test = X_test.fillna(value = 0)

In [37]:
#filling in missing values

X_test = X_test.fillna(method='bfill')
X_test = X_test.fillna(value = 0)

In [38]:
# getting predictions

pred = neigh.predict(X_test)

In [42]:
# creating submission file


sol = pd.DataFrame({"ID" : test_df['ID'], "attempts_range" : pred})

In [43]:
# saving it

sol.to_csv("submission.csv", index=False)

In [44]:
sol.head()

ID  attempts_range
0   user_856_prob_5822               1
1   user_846_prob_5822               1
2  user_2183_prob_5822               1
3  user_2553_prob_5822               1
4   user_856_prob_1868               1

In [45]:
sol['attempts_ range'].value_counts()

KeyError: 'attempts_ range'